const weather = {
	0: ["Soleil", "☀️", "https://cdn.futura-sciences.com/buildsv6/images/wide1920/6/2/b/62b0677a23_129709_soleil-brille.jpg"],
	1: ["Peu nuageux", "🌤", "https://img.medi1tv.com/meteo_270219.jpg"],
	2: ["Ciel voilé", "⛅️", "https://d2p1ubzgqn8tkf.cloudfront.net/article/1034114/lg_05a71d9f2d206e8a71d9f2d20aca71v_.jpg"],
	3: ["Nuageux", "🌥", "https://img.freepik.com/photos-gratuite/ciel-nuageux-temps-maussade-nuages-gris-photo-haute-qualite_153912-1390.jpg"],
	4: ["Très nuageux", "☁️", "https://www.archi7.net/J34/images/QR/2018-06-couleurs-nuages-storm-clouds-426271-pixabay.jpg"],
	5: ["Couvert", "⛅️", "https://www.archi7.net/J34/images/QR/2018-06-couleurs-nuages-storm-clouds-426271-pixabay.jpg"],
	6: ["Brouillard", "☁️", "https://www.ecopark-cdg.com/wp-content/uploads/2018/03/conduire-sous-le-brouillard-1200x675.jpg"],
	7: ["Brouillard givrant", "☁️", "https://www.agate-france.com/img/pictures/2019/20191231/thumbnail/1912315491.png"],
	10: ["Pluie faible", "🌦", "https://static.actu.fr/uploads/2022/03/adobestock-366903907.jpeg"],
	11: ["Pluie modérée", "🌧", "https://static.actu.fr/uploads/2022/03/adobestock-366903907.jpeg"],
	12: ["Pluie forte", "⛈", "https://www.lalibre.be/resizer/_M9tdn3-rSL_7w5vc7r1IX3VUt8=/768x512/filters:quality(70):format(jpg):focal(1275x858:1285x848)/cloudfront-eu-central-1.images.arcpublishing.com/ipmgroup/QKA7UIO76FHQFNKLFMXV3W6B2M.jpg"],
	13: ["Pluie faible verglaçante", "t"],
	14: ["Pluie modérée verglaçante", "t"],
	15: ["Pluie forte verglaçante", "t"],
	16: ["Bruine", "t"],
	20: ["Neige faible", "t"],
	21: ["Neige modérée", "t"],
	22: ["Neige forte", "t"],
	30: ["Pluie et neige mêlées faibles", "t"],
	31: ["Pluie et neige mêlées modérées", "t"],
	32: ["Pluie et neige mêlées fortes", "t"],
	40: ["Averses de pluie locales et faibles", "t"],
	41: ["Averses de pluie locales", "🌧", "https://www.lalibre.be/resizer/_M9tdn3-rSL_7w5vc7r1IX3VUt8=/768x512/filters:quality(70):format(jpg):focal(1275x858:1285x848)/cloudfront-eu-central-1.images.arcpublishing.com/ipmgroup/QKA7UIO76FHQFNKLFMXV3W6B2M.jpg"],
	42: ["Averses locales et fortes", "t"],
	43: ["Averses de pluie faibles", "t"],
	44: ["Averses de pluie", "t"],
	45: ["Averses de pluie fortes", "t"],
	46: ["Averses de pluie faibles et fréquentes", "t"],
	47: ["Averses de pluie fréquentes", "t"],
	48: ["Averses de pluie fortes et fréquentes", "t"],
	60: ["Averses de neige localisées et faibles", "t"],
	61: ["Averses de neige localisées", "t"],
	62: ["Averses de neige localisées et fortes", "t"],
	63: ["Averses de neige faibles", "t"],
	64: ["Averses de neige", "t"],
	65: ["Averses de neige fortes", "t"],
	66: ["Averses de neige faibles et fréquentes", "t"],
	67: ["Averses de neige fréquentes", "t"],
	68: ["Averses de neige fortes et fréquentes", "t"],
	70: ["Averses de pluie et neige mêlées localisées et faibles", "t"],
	71: ["Averses de pluie et neige mêlées localisées", "t"],
	72: ["Averses de pluie et neige mêlées localisées et fortes", "t"],
	73: ["Averses de pluie et neige mêlées faibles", "t"],
	74: ["Averses de pluie et neige mêlées", "t"],
	75: ["Averses de pluie et neige mêlées fortes", "t"],
	76: ["Averses de pluie et neige mêlées faibles et nombreuses", "t"],
	77: ["Averses de pluie et neige mêlées fréquentes", "t"],
	78: ["Averses de pluie et neige mêlées fortes et fréquentes", "t"],
	100:[ "Orages faibles et locaux", "t"],
	101:[ "Orages locaux", "t"],
	102:[ "Orages fort et locaux", "t"],
	103:[ "Orages faibles", "t"],
	104:[ "Orages", "t"],
	105:[ "Orages forts", "t"],
	106:[ "Orages faibles et fréquents", "t"],
	107:[ "Orages fréquents", "t"],
	108:[ "Orages forts et fréquents", "t"],
	120:[ "Orages faibles et locaux de neige ou grésil", "t"],
	121:[ "Orages locaux de neige ou grésil", "t"],
	122:[ "Orages locaux de neige ou grésil", "t"],
	123:[ "Orages faibles de neige ou grésil", "t"],
	124:[ "Orages de neige ou grésil", "t"],
	125:[ "Orages de neige ou grésil", "t"],
	126:[ "Orages faibles et fréquents de neige ou grésil", "t"],
	127:[ "Orages fréquents de neige ou grésil", "t"],
	128:[ "Orages fréquents de neige ou grésil", "t"],
	130:[ "Orages faibles et locaux de pluie et neige mêlées ou grésil", "t"],
	131:[ "Orages locaux de pluie et neige mêlées ou grésil", "t"],
	132:[ "Orages fort et locaux de pluie et neige mêlées ou grésil", "t"],
	133:[ "Orages faibles de pluie et neige mêlées ou grésil", "t"],
	134:[ "Orages de pluie et neige mêlées ou grésil", "t"],
	135:[ "Orages forts de pluie et neige mêlées ou grésil", "t"],
	136:[ "Orages faibles et fréquents de pluie et neige mêlées ou grésil", "t"],
	137:[ "Orages fréquents de pluie et neige mêlées ou grésil", "t"],
	138:[ "Orages forts et fréquents de pluie et neige mêlées ou grésil", "t"],
	140:[ "Pluies orageuses", "t"],
	141:[ "Pluie et neige mêlées à caractère orageux", "t"],
	142:[ "Neige à caractère orageux", "t"],
	210:[ "Pluie faible intermittente", "t"],
	211:[ "Pluie modérée intermittente", "t"],
	212:[ "Pluie forte intermittente", "t"],
	220:[ "Neige faible intermittente", "t"],
	221:[ "Neige modérée intermittente", "t"],
	222:[ "Neige forte intermittente", "t"],
	230:[ "Pluie et neige mêlées", "t"],
	231:[ "Pluie et neige mêlées", "t"],
	232:[ "Pluie et neige mêlées", "t"],
	235:[ "Averses de grêle", "t"],
}

export default weather